### ISSUE TITLE
Update to 1.17?

### ISSUE THREAD

**Issue by strikerrocker** [YTG1234/fabric-recipe-conditions#5]
Hey sorry for seeming like an annoying user who requests mod updates, i have tried contacting you via both discord and matrix but you haven't responded. My mod depends on your mod for its conditional recipe and I can't port it to 1.17. I am opening this issue for getting an clarification whether you have any plans on updating it 1.17.

**Comment by YTG1234** [comment]
Updating it right now!

**Comment by strikerrocker** [comment]
Thanks.

**Comment by YTG1234** [comment]
Hmm, I tried to rebuild the library for 1.17 without any code changes, and it appears to compile just fine. Does the current version not work with 1.17?

**Comment by strikerrocker** [comment]
Hey I didn't check if the old version works in 1.17 and assumed it wouldn't. I am sorry for wasting your time.

**Comment by YTG1234** [comment]
Java 16 does have some nice features that would be of use to me and I would like to update, so I'm reopening this.

**Comment by YTG1234** [comment]
The new version (0.4.1) is not published anywhere just yet, so you'd need to use Jitpack.

**Comment by strikerrocker** [comment]
Thanks for updating.

**Comment by strikerrocker** [comment]
Hey i tried using Jitpack but it only uses java 8 by default and i cant change the java version on my side. For now i am going use the 0.4.0 version.
